MODULE CLASS_FACULTY
	IMPLICIT NONE

	TYPE FACULTY
			INTEGER					IDNUM
			CHARACTER*4				DEPT
			CHARACTER*9				RANK
			CHARACTER*13			NAME
			REAL					PAY
	END TYPE FACULTY

    CONTAINS

	CHARACTER(100) FUNCTION PRINT_FACULTY(FAC_MEM)
        IMPLICIT NONE
        CHARACTER(100) RESULT
        CHARACTER (8) ID_NUMBER
        CHARACTER(10) PAY_NUMBER
        TYPE(FACULTY) FAC_MEM
        WRITE(ID_NUMBER,'(i8)')FAC_MEM%IDNUM
        WRITE(PAY_NUMBER,'(f9.2)')FAC_MEM%PAY
        RESULT = ID_NUMBER // ' '// FAC_MEM%NAME// ' '// FAC_MEM%DEPT// ' '// FAC_MEM%RANK// ' '// PAY_NUMBER
        !WRITE(*,*) FAC_MEM%IDNUM, ' ', FAC_MEM%NAME, ' ', FAC_MEM%DEPT, ' ', FAC_MEM%RANK, ' ', FAC_MEM %PAY
    END FUNCTION PRINT_FACULTY

END MODULE CLASS_FACULTY

