MODULE CLASS_FACULTY
	IMPLICIT NONE
	TYPE FACULTY
			INTEGER					IDNUM
			CHARACTER*4				DEPT
			CHARACTER*9				RANK
			CHARACTER*13			NAME
			REAL					PAY
	END TYPE FACULTY

END MODULE CLASS_FACULTY
