MODULE FINDER
    USE CLASS_FACULTY
    IMPLICIT NONE

    CONTAINS

    INTEGER FUNCTION FIND_FACULTY_MEMBER(IDNUM_LOOKING, FACULTY_LIST, HEAD_INDEX)

        INTEGER                             :: IDNUM_LOOKING,I,HEAD_INDEX
        TYPE(FACULTY), DIMENSION(100)       :: FACULTY_LIST
        FIND_FACULTY_MEMBER = -1
        DO I=1,100,1

        END DO
        RETURN
    END FUNCTION

END MODULE FINDER
