MODULE FINDER
    USE CLASS_FACULTY
    IMPLICIT NONE

    CONTAINS

    INTEGER FUNCTION FIND_FACULTY_MEMBER(IDNUM, FACULTY_LIST, HEAD_INDEX)

        INTEGER                             :: IDNUM,I,HEAD_INDEX, INDEX, NEXT
        TYPE(FACULTY), DIMENSION(100)       :: FACULTY_LIST

        INDEX = -1;
        NEXT = HEAD_INDEX
        DO

        END DO
        FIND_FACULTY_MEMBER = INDEX
    END FUNCTION

END MODULE FINDER
