MODULE FINDER
    USE CLASS_FACULTY
    IMPLICIT NONE

    CONTAINS

    INTEGER FUNCTION FIND_FACULTY_MEMBER(IDNUM_LOOKING, FACULTY_LIST,INDEX_LIST)

        INTEGER                             :: IDNUM_LOOKING,I
        TYPE(FACULTY), DIMENSION(100)       :: FACULTY_LIST
        TYPE(INTEGER), DIMENSION(100)       :: INDEX_LIST
        FIND_FACULTY_MEMBER = -1
        DO I=1,100,1
            IF(INDEX_LIST(I).NE.-99) THEN
                IF(FACULTY_LIST(INDEX_LIST(I))%IDNUM.EQ.IDNUM_LOOKING) THEN
                    FIND_FACULTY_MEMBER = INDEX_LIST(I)
                    EXIT
                END IF
            END IF
        END DO
        RETURN
    END FUNCTION

END MODULE FINDER
