MODULE INSERT_AND_DELETE
	
	IMPLICIT NONE

	CONTAINS

	SUBROUTINE INSERT_OP(STR)
			CHARACTER*66 	STR
			INTEGER			IDNUM
			CHARACTER*13	NAME
			CHARACTER*4		DEPT
			CHARACTER*9		RANK
			REAL			PAY

			READ(STR, 300) IDNUM, NAME, DEPT, RANK, PAY
		300	FORMAT(3X, I8, 1X, A13, 1X, A4, 11X, A9, 8X, F9.2)
			WRITE(6, *) "** In INSERT_OP w/ ID = ", IDNUM, " NAME = ", NAME, " **"
			RETURN
	END SUBROUTINE INSERT_OP

		

	SUBROUTINE DELETE_OP(STR)
			CHARACTER*66 	STR
			INTEGER 		IDNUM

			READ(STR, 400) IDNUM
		400	FORMAT(3X, I8)
			WRITE(6, *) "** In DELETE_OP w/ ID = ", IDNUM, " **"
			RETURN
	END SUBROUTINE DELETE_OP

END MODULE INSERT_AND_DELETE