MODULE NODEMODULE
	IMPLICIT NONE
	TYPE NODE
		CHARACTER(LEN=66) ::	INPUT_STRING
		CHARACTER*2				COMMAND
		INTEGER					IDNUM
		CHARACTER*4				DEPT
		CHARACTER*9				RANK
		REAL					PAY
		TYPE (NODE), POINTER ::	HEAD, LAST
	END TYPE NODE

	CONTAINS
	SUBROUTINE ADD()
	END SUBROUTINE ADD

	SUBROUTINE DELETE()
	END SUBROUTINE DELETE

	SUBROUTINE PRINT_INDIVIDUAL()
	END SUBROUTINE PRINT_INDIVIDUAL


END MODULE NODEMODULE
