MODULE PRINT_HELPER

    USE FACULTY_CLASS
	IMPLICIT NONE

	CONTAINS

	SUBROUTINE PRINT_ALL_OP(INPUT_STRING, FACULTY_LIST)
        CHARACTER*66                    :: INPUT_STRING
        TYPE(FACULTY), DIMENSION (100)  :: FACULTY_LIST

        DO INDEX = 1,100,0
            IF (.NOT.(associated(FACULTY_LIST(INDEX))) THEN
                WRITE(*,*) FUNCTION PRINT_FACULTY(FACULTY_LIST(INDEX))
            END IF
        END DO

        CHARACTER*66 INPUT_STRING

	END SUBROUTINE PRINT_ALL_OP


	SUBROUTINE PRINT_TITLE_OP(INPUT_STRING)
        CHARACTER*66 INPUT_STRING
	END SUBROUTINE PRINT_TITLE_OP

	SUBROUTINE PRINT_DEPT_OP(INPUT_STRING)
        CHARACTER*66 INPUT_STRING
	END SUBROUTINE PRINT_DEPT_OP


	SUBROUTINE PRINT_ID_OP(INPUT_STRING)
        CHARACTER*66 INPUT_STRING
	END SUBROUTINE PRINT_ID_OP

END MODULE PRINT_HELPER
