MODULE UPDATE_HELPER
	
	IMPLICIT NONE

	CONTAINS

	SUBROUTINE UPDATE_DEPT_OP()
	END SUBROUTINE UPDATE_DEPT_OP

	SUBROUTINE UPDATE_TITLE_OP()
			
	END SUBROUTINE UPDATE_TITLE_OP

	SUBROUTINE UPDATE_PAY_OP()
	END SUBROUTINE UPDATE_PAY_OP

END MODULE UPDATE_HELPER