MODULE UPDATE_HELPER

	USE NODE
	
	IMPLICIT NONE

	CONTAINS

	SUBROUTINE UPDATE_DEPT_OP(INPUT_STRING)
	END SUBROUTINE UPDATE_DEPT_OP

	SUBROUTINE UPDATE_TITLE_OP(INPUT_STRING)
	END SUBROUTINE UPDATE_TITLE_OP

	SUBROUTINE UPDATE_PAY_OP(INPUT_STRING)
	END SUBROUTINE UPDATE_PAY_OP

END MODULE UPDATE_HELPER